{{- if .Values.frontend.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kvie-chart.fullname" . }}-frontend
  labels:
    {{- include "kvie-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kvie-chart.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.backend.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kvie-chart.fullname" . }}-backend
  labels:
    {{- include "kvie-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kvie-chart.selectorLabels" . | nindent 4 }}
{{- end }}
